### PR TITLE
update font definitions, add class generator

### PR DESCRIPTION
**Pull request by koenpunt**
With the codepoints file provided in the Google repo, the enum can now easily be generated.

https://github.com/google/material-design-icons/tree/master/iconfont

### CODE REVIEW

**Comment by koenpunt** [comment]
I notice a slight difference in line height, compared to the previous font. @kitasuke did you modify the font in any way? Or just used the one supplied by Google?

**Comment by koenpunt** [comment]
Turns out this problem only occurs for `UIBarButtonItem`'s

**Comment by kitasuke** [comment]
Thanks for your PR and research!
I'll look into this as soon as possible.

**Comment by kitasuke** [comment]
I like your idea that script file generates enum is put in Pod directory.
I'm new to Ruby, but looks nice!

**Pull request merged**
