### PR TITLE
Swift3.0

### PR DESCRIPTION
**Pull request by kitasuke**

### CODE REVIEW

**Comment by se-rg-os** [comment]
Hi, 
I am very keen in using your approach of using Material font but I am using Swift 3.x already.

I've found that ruby String has [camelize](http://apidock.com/rails/String/camelize) function, but it needs some dependencies for it.

But I assume adding this to `generate.rb` file may help as well:

```
class String 
    def camelize(uppercase_first_letter = true)
      string = self
      if uppercase_first_letter
        string = string.sub(/^[a-z\d]*/) { $&.capitalize }
      else
        string = string.sub(/^(?:(?=\b|[A-Z_])|\w)/) { $&.downcase }
      end
      string.gsub(/(?:_|(\/))([a-z\d]*)/) { "#{$1}#{$2.capitalize}" }.gsub('/', '::')
    end
end
```

Then this `name = name.split('_').collect(&:capitalize).join` can be changed to:

- `name = name.camelize` for Swift 2.x
- `name = name.camelize(false)` for Swift 3.x where enums should start with low case.

I am also thinking how to handle case when first character is digit in a better way (right now only `3` is handled). 

I may investigate this and create separate PR for `generate.rb` script changes, although I am mobile developer, so not so strong in Ruby :)

**Comment by se-rg-os** [comment]
Sorry for bothering, I've quickly made simple function to handle case with digits:

```
    def undigitalize(digitalize_only_first_symbol = true)
      string = self
      if digitalize_only_first_symbol
        regex = "^[0-9]"
      else
        regex = "[0-9]"
      end
      string = string.gsub(/#{regex}/, '0' => 'zero_', '1' => 'one_', '2' => 'two_', '3' => 'three_', '4' => 'four_', '5' => 'five_', '6' => 'six_', '7' => 'seven_', '8' => 'eight_', '9' => 'nine_') 
    end
```

as a result, we may get something like this:

```
"123hello_world".undigitalize.camelize(false)
=> "one23helloWorld"

"123hello_world".undigitalize(false).camelize(false)
=> "oneTwoThreeHelloWorld"
```

**Comment by kitasuke** [comment]
That's awesome! I can finally merge this PR. Can you commit and push or create new PR with your change? I appreciate for your help.

**Comment by se-rg-os** [comment]
@kitasuke I am happy to help 👍 
I will create PR (hopefully during this week) with changes in `generate.rb`

I've faced one issue when trying updated `generate.rb` - some icons names are actually reserved words in Swift. 

I've found 4: `class`, `public`, `extension`, `repeat`.

I see several solutions: 

- adding prefix (e.g. "mif") to all names
- handling only these 4 names for now and adding some prefix/suffix to them only
- your ideas

**Comment by kitasuke** [comment]
Thanks @sergii-frost!

Let's add `mif_` prefix!

**Comment by Gruneau** [comment]
this PR needs some love! 💃

**Comment by kousun12** [comment]
@kitasuke any plans on merging this?

**Comment by ArturGasparyan** [comment]
Hello! Any updates on this? The new Xcode update broke my app due to this library (see created issue). Please help!

**Comment by se-rg-os** [comment]
I have my changes on another laptop, but will try to create PR during tomorrow.

As discussed earlier, there is prefix needed for all the icons, so these changes will be kinda breaking.

**Comment by se-rg-os** [comment]
@kitasuke I will not be able to commit to the same PR, but I will create another one. 
Previously we agreed on adding "mif_" as prefix. what if we get rid of "_" and just add "mif" as a prefix to all camelized names (as they appear now) ?

**Comment by se-rg-os** [comment]
screen shot 2017-04-05 at 21 37 03

**Comment by ArturGasparyan** [comment]
Any updates here? My project relies on this framework...

**Pull request closed without merging**
